### ISSUE TITLE
The Project Server Migration Doc is missing steps

### ISSUE THREAD

**Issue by SteveZFlorida** [MicrosoftDocs/OfficeDocs-ProjectServer#37]
**To: MS Project Server Product team,** 

The office migration docs for both Project Server 2016 and 2019 migrations titled "Upgrading to Project Server" are missing a key step. I opened a case with Microsoft and they asked me to submit the issue here instead of taking action after confirming there is an issue with the documentation and a separate issue with Project Server 2019. 

**Documentation feedback:** The command Migrate-SPProjectDatabase is missing from the articles and is a key step to successfully migrate from Project Server 2013 to Project Server 2016. 

Please verify the steps and add the missing information as the steps provided will not complete a migration. 

**In addition**, Project Server 2019 is completely missing the Powershell command Migrate-SPProjectDatabase. This was also confirmed by the Microsoft support team. Because Project Server 2019 is new, there may not have been companies attempting a migration yet.  

I hope this helps other customers migrate to Project Server. If you have any questions, please reach out to me. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05262b2f-6cbc-5cda-fe7a-50e35ed0cc4e
* Version Independent ID: 58d80865-5e58-70e5-6993-19d047e34e01
* Content: [Upgrading to Project Server 2019](https://docs.microsoft.com/en-us/Project/upgrading-to-project-server-2019#feedback)
* Content Source: [Project/upgrading-to-project-server-2019.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/Project/upgrading-to-project-server-2019.md)
* Product: **project-server-itpro**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by tseward** [comment]
As for Project Server 2019, this makes sense. Microsoft requires you to upgrade from 2013 -> 2016 (running the Migrate cmdlet) -> 2019. Since there is nothing to 'migrate' for Project Server as there is from 2013 to 2016, the cmdlet isn't required.

**Comment by efrene** [comment]
Thanks so much for your interest in the content.   I am following up with this, but I believe that the Migrate-SPProjectDatabase isn't required for migration to Project Server 2019 since the Project Database doesn't exist in Project Server 2016, as I believe it was then a part of the SharePoint Content database.   I also am looking at the "Upgrading to Project Server 2016" article to see if the Migrate-SPProjectDatabase cmdlet isn't present (and I agree, it should be present), but I am seeing it in the content.  I will make sure to verify this again, just to make sure.  Again, thanks so much for taking the time to look at the content and for your interest in it's accuracy.

**Comment by efrene** [comment]
@SteveZFlorida - I just confirmed with support that my above comment was valid.  If you have a case number, I can follow up with the person you are talking with on the Microsoft Support team.  Just let me know.  Thanks again in your interest in making the content better.

@tseward - Thank you for feedback on this as well.
