### ISSUE TITLE
Project P3 is not listed as a sublicense

### ISSUE THREAD

**Issue by EmiliaDeica** [MicrosoftDocs/OfficeDocs-ProjectServer#74]
I believe there is an error here. With both a real tenant and a demo tenant, I added a Project Plan 1 license and I don't see Project P3. The 3 sublicenses listed are: Common Data Service for Project P1, Project P1 and SharePoint Online (Plan 1)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0995559d-622b-c2d1-3133-9cf267de4a65
* Version Independent ID: b21ea8a9-c3fa-9cf5-ae66-58ac96cf1f6d
* Content: [Turn off Project for the web  - Project for the web](https://docs.microsoft.com/en-ca/project-for-the-web/turn-project-for-the-web-off)
* Content Source: [ProjectWeb/turn-project-for-the-web-off.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/ProjectWeb/turn-project-for-the-web-off.md)
* Service: ****
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by efrene** [comment]
Thanks for the feedback on this.  I'll update the article to make it clearer that Project P3 is only available through the Project Plan 3 or Plan 5 license, and thanks for pointing this out.  The article assumed that someone with a Project Plan 1 license would not want to turn off the service for the user, since it only provides you Project for the web.  While someone with a Project Plan 3 or Plan 5 license might want to turn it off because they only want to use the other services (like Project Online) for now.  But you are correct - the article needs to be clearer about the Project Plan 1 license. Thanks again!

**Comment by EmiliaDeica** [comment]
Thanks a lot, that's great.
________________________________
De : Efren Edwards <notifications@github.com>
Envoyé : 5 février 2020 12:42
À : MicrosoftDocs/OfficeDocs-ProjectServer <OfficeDocs-ProjectServer@noreply.github.com>
Cc : EmiliaDeica <calamity_13@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [MicrosoftDocs/OfficeDocs-ProjectServer] Project P3 is not listed as a sublicense (#74)


Thanks for the feedback on this. I'll update the article to make it clearer that Project P3 is only available through the Project Plan 3 or Plan 5 license, and thanks for pointing this out. The article assumed that someone with a Project Plan 1 license would not want to turn off the service for the user, since it only provides you Project for the web. While someone with a Project Plan 3 or Plan 5 license might want to turn it off because they only want to use the other services (like Project Online) for now. But you are correct - the article needs to be clearer about the Project Plan 1 license. Thanks again!

**Comment by scanum** [comment]
@EmiliaDeica Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
